/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Categories: typeof import('./src/components/categories/Categories.vue')['default']
    Info: typeof import('./src/components/info/Info.vue')['default']
    Menu: typeof import('./src/components/menu/Menu.vue')['default']
    MenuItem: typeof import('./src/components/menu/MenuItem.vue')['default']
    Post: typeof import('./src/components/post/Post.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/search/Search.vue')['default']
    TAffix: typeof import('tdesign-vue-next')['Affix']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TBackTop: typeof import('tdesign-vue-next')['BackTop']
    TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCol: typeof import('tdesign-vue-next')['Col']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDivier: typeof import('tdesign-vue-next')['Divier']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TDropdownItem: typeof import('tdesign-vue-next')['DropdownItem']
    TDropdownMenu: typeof import('tdesign-vue-next')['DropdownMenu']
    TFooter: typeof import('tdesign-vue-next')['Footer']
    THeader: typeof import('tdesign-vue-next')['Header']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TImage: typeof import('tdesign-vue-next')['Image']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLink: typeof import('tdesign-vue-next')['Link']
    TList: typeof import('tdesign-vue-next')['List']
    TListItem: typeof import('tdesign-vue-next')['ListItem']
    TListItemMeta: typeof import('tdesign-vue-next')['ListItemMeta']
    TMain: typeof import('tdesign-vue-next')['Main']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TPagination: typeof import('tdesign-vue-next')['Pagination']
    TPopup: typeof import('tdesign-vue-next')['Popup']
    TRow: typeof import('tdesign-vue-next')['Row']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TStatistic: typeof import('tdesign-vue-next')['Statistic']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTypographyParagraph: typeof import('tdesign-vue-next')['Paragraph']
    TTypographyText: typeof import('tdesign-vue-next')['Text']
    TTypographyTitle: typeof import('tdesign-vue-next')['Title']
  }
}
